name: Android CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Android ENV Production
      id: android_env_pro
      if: contains(toJSON(github.ref), 'master')
      run: |
        echo BASE_URL='https://daiku-app.goenway.com/' >> $GITHUB_ENV
        echo KEYSTORE_BASE64=${{ secrets.KEYSTORE_BASE64_PRD }} >> $GITHUB_ENV
        echo KEY_ALIAS=${{ secrets.KEY_ALIAS_PRD }} >> $GITHUB_ENV
        echo KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD_PRD }} >> $GITHUB_ENV
        echo KEY_PASSWORD=${{ secrets.KEY_PASSWORD_PRD }} >> $GITHUB_ENV
        echo TF_VAR_ENV=prd >> $GITHUB_ENV
        echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_PRD}} >> $GITHUB_ENV
        echo FIREBASE_APPLICATION_ID=${{ secrets.FIREBASE_APPLICATION_ID_PRD}} >> $GITHUB_ENV
        echo FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_PRD}} >> $GITHUB_ENV

    - name: Android ENV Develop
      id: android_env_dev
      if: contains(toJSON(github.ref), 'develop') || contains(toJSON(github.ref), 'feature') || github.event_name == 'pull_request'
      run: |
        echo BASE_URL='https://daiku-app.dev.goenway.com/' >> $GITHUB_ENV
        echo KEYSTORE_BASE64=${{ secrets.KEYSTORE_BASE64_DEV }} >> $GITHUB_ENV
        echo KEY_ALIAS=${{ secrets.KEY_ALIAS_DEV }} >> $GITHUB_ENV
        echo KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD_DEV }} >> $GITHUB_ENV
        echo KEY_PASSWORD=${{ secrets.KEY_PASSWORD_DEV }} >> $GITHUB_ENV
        echo TF_VAR_ENV=dev >> $GITHUB_ENV
        echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_DEV}} >> $GITHUB_ENV
        echo FIREBASE_APPLICATION_ID=${{ secrets.FIREBASE_APPLICATION_ID_DEV}} >> $GITHUB_ENV
        echo FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_DEV}} >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      if: (contains(toJSON(github.ref), 'develop') || contains(toJSON(github.ref), 'master')) && github.event_name == 'push'
      run: |
        if [[ -n "${{ env.KEYSTORE_BASE64 }}" ]]; then
          echo "${{ env.KEYSTORE_BASE64 }}" | base64 -d > ${{ env.TF_VAR_ENV }}-release.keystore
          export KEYSTORE_PASSWORD="${{ env.KEYSTORE_PASSWORD }}"
          export KEY_ALIAS="${{ env.KEY_ALIAS }}"
          export KEY_PASSWORD="${{ env.KEY_PASSWORD }}"
        fi
        ./gradlew build :app:assembleDevRelease

    - name: APK Download
      if: (contains(toJSON(github.ref), 'develop') || contains(toJSON(github.ref), 'master')) && github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: app/build/outputs/


    - name: APK Download Lint Result
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-result
        path: /home/runner/work/daiku-android/daiku-android/auth/lint-baseline.xml